version: 2
updates:
  - package-ecosystem: "bundler"
    directory: /
    schedule:
      interval: "weekly"
      time: "04:00"
      timezone: "Australia/Brisbane"
    # Disable dependabot for this repository.
    ignore:
      - dependency-name: "*"
