AllCops:
  TargetRubyVersion: 2.3
  Exclude:
    - db/schema.rb

Rails:
  Enabled: true

Rails/Output:
  Exclude:
    - db/seeds.rb

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Exclude:
    - db/migrate/*.rb

Metrics/AbcSize:
  Exclude:
    - db/migrate/*.rb
