inherit_gem:
  aaf-gumboot: aaf-rubocop.yml

AllCops:
  NewCops: enable
  Exclude:
    - bin/**
    - db/**/*

Layout/LineLength:
  Max: 120

Style/StderrPuts:
  Enabled: false

Rails/DynamicFindBy:
  Whitelist:
    - find_by_sql
    - find_by_identifying_attribute

Naming/MethodParameterName:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Rails/InverseOf:
  Enabled: false

Lint/MissingSuper:
  Enabled: false

