default: &default
  adapter: mysql2
  encoding: utf8
  collation: utf8_bin
  username: <%= ENV['REPORTING_DB_USERNAME'] || 'reporting_app' %>
  password: "<%= ENV['REPORTING_DB_PASSWORD'] || 'password' %>"
  host: <%= ENV['REPORTING_DB_HOST'] || '127.0.0.1' %>
  port: <%= ENV['REPORTING_DB_PORT'] || 3306 %>
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: <%= ENV['REPORTING_DB_NAME'] || 'reporting_dev' %>

test:
  <<: *default
  database: reporting_test

production:
  <<: *default
  database: <%= ENV['REPORTING_DB_NAME'] || 'reporting_production' %>
