default: &default
  adapter: mysql2
  collation: utf8mb4_bin
  encoding: utf8mb4
  host: <%= ENV['REPORTING_DB_HOST'] || '127.0.0.1' %>
  password: "<%= ENV['REPORTING_DB_PASSWORD'] || 'password' %>"
  pool: 5
  port: <%= ENV['REPORTING_DB_PORT'] || 3306 %>
  timeout: 5000
  username: <%= ENV['REPORTING_DB_USERNAME'] || 'reporting_app' %>
development:
  <<: *default
  database: <%= ENV['REPORTING_DB_NAME'] || 'reporting_dev' %>
  read_timeout: <%= ENV.fetch('MYSQL_MAX_EXECUTION_TIME_SECONDS') { 60 } %>
  write_timeout: <%= ENV.fetch('MYSQL_MAX_EXECUTION_TIME_SECONDS') { 60 } %>
production:
  <<: *default
  database: <%= ENV['REPORTING_DB_NAME'] || 'reporting_production' %>
  read_timeout: <%= ENV['MYSQL_MAX_EXECUTION_TIME_SECONDS'] %>
  write_timeout: <%= ENV['MYSQL_MAX_EXECUTION_TIME_SECONDS'] %>
test:
  <<: *default
  database: reporting_test
