default: &default
  url: http://127.0.0.1:9200

development:
  <<: *default
  index: reporting_service

test:
  <<: *default
  index: reporting_service_test

production:
  <<: *default
  index: <%= ENV['REPORTING_ELASTICSEARCH_INDEX'] %>
